"""add_password_reset_tokens

Adds the ``password_reset_tokens`` table backing the forgot/reset-password
flow (``POST /auth/forgot-password``, ``POST /auth/reset-password``). The raw
token is never stored — only its SHA-256 digest (mirroring ``refresh_tokens``).

Revision ID: 0008
Revises: 0007
Create Date: 2026-09-02

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0008"
down_revision: Union[str, None] = "0007"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "password_reset_tokens",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("used_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("password_reset_tokens_user_id_fkey"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("password_reset_tokens_pkey")),
    )
    op.create_index(
        op.f("password_reset_tokens_token_hash_idx"),
        "password_reset_tokens",
        ["token_hash"],
        unique=False,
    )
    op.create_index(
        op.f("password_reset_tokens_expires_at_idx"),
        "password_reset_tokens",
        ["expires_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("password_reset_tokens_expires_at_idx"), table_name="password_reset_tokens")
    op.drop_index(op.f("password_reset_tokens_token_hash_idx"), table_name="password_reset_tokens")
    op.drop_table("password_reset_tokens")
    # ### end Alembic commands ###
