"""initial_schema

Revision ID: eb88597519c9
Revises: 
Create Date: 2026-07-27 14:15:06.488703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb88597519c9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('node_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('location_name', sa.String(length=200), nullable=True),
    sa.Column('lat', sa.Double(), nullable=True),
    sa.Column('lon', sa.Double(), nullable=True),
    sa.Column('firmware_version', sa.String(length=50), nullable=True),
    sa.Column('reading_interval', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('registered_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('node_id', name=op.f('nodes_pkey'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('notification_prefs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('users_email_idx'), 'users', ['email'], unique=True)
    op.create_index(op.f('users_username_idx'), 'users', ['username'], unique=True)
    op.create_table('alerts',
    sa.Column('alert_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('node_id', sa.String(length=50), nullable=False),
    sa.Column('parameter', sa.String(length=50), nullable=False),
    sa.Column('value', sa.REAL(), nullable=False),
    sa.Column('threshold', sa.REAL(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('triggered_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('acknowledged_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], name=op.f('alerts_acknowledged_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.node_id'], name=op.f('alerts_node_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('alert_id', name=op.f('alerts_pkey'))
    )
    op.create_index(op.f('alerts_node_id_idx'), 'alerts', ['node_id'], unique=False)
    op.create_table('hourly_agg',
    sa.Column('bucket', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('node_id', sa.String(length=50), nullable=False),
    sa.Column('avg_temperature', sa.REAL(), nullable=True),
    sa.Column('avg_humidity', sa.REAL(), nullable=True),
    sa.Column('avg_pm25', sa.REAL(), nullable=True),
    sa.Column('avg_pm10', sa.REAL(), nullable=True),
    sa.Column('max_aqi', sa.SmallInteger(), nullable=True),
    sa.Column('min_aqi', sa.SmallInteger(), nullable=True),
    sa.Column('avg_aqi', sa.REAL(), nullable=True),
    sa.Column('anomaly_count', sa.Integer(), nullable=False),
    sa.Column('reading_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.node_id'], name=op.f('hourly_agg_node_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bucket', 'node_id', name='hourly_agg_pkey')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('refresh_tokens_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('refresh_tokens_pkey'))
    )
    op.create_index(op.f('refresh_tokens_token_hash_idx'), 'refresh_tokens', ['token_hash'], unique=False)
    op.create_index(op.f('refresh_tokens_user_id_idx'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('sensor_readings',
    sa.Column('time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('node_id', sa.String(length=50), nullable=False),
    sa.Column('temperature', sa.REAL(), nullable=True),
    sa.Column('humidity', sa.REAL(), nullable=True),
    sa.Column('pressure', sa.REAL(), nullable=True),
    sa.Column('voc_ohm', sa.REAL(), nullable=True),
    sa.Column('mq135_ppm', sa.REAL(), nullable=True),
    sa.Column('pm1', sa.REAL(), nullable=True),
    sa.Column('pm25', sa.REAL(), nullable=True),
    sa.Column('pm10', sa.REAL(), nullable=True),
    sa.Column('battery_v', sa.REAL(), nullable=True),
    sa.Column('fuzzy_score', sa.REAL(), nullable=True),
    sa.Column('aqi', sa.SmallInteger(), nullable=True),
    sa.Column('aqi_category', sa.String(length=40), nullable=True),
    sa.Column('is_anomaly', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.node_id'], name=op.f('sensor_readings_node_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('time', 'node_id', name='sensor_readings_pkey')
    )
    # ── Performance indexes for sensor_readings (common query patterns) ──
    op.create_index('idx_readings_node_time', 'sensor_readings',
                    ['node_id', sa.text('time DESC')])
    op.create_index('idx_readings_time', 'sensor_readings',
                    [sa.text('time DESC')])
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('system_settings_updated_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('key', name=op.f('system_settings_pkey'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_settings')
    op.drop_index('idx_readings_time', table_name='sensor_readings')
    op.drop_index('idx_readings_node_time', table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_index(op.f('refresh_tokens_user_id_idx'), table_name='refresh_tokens')
    op.drop_index(op.f('refresh_tokens_token_hash_idx'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('hourly_agg')
    op.drop_index(op.f('alerts_node_id_idx'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('users_username_idx'), table_name='users')
    op.drop_index(op.f('users_email_idx'), table_name='users')
    op.drop_table('users')
    op.drop_table('nodes')
    # ### end Alembic commands ###
